### ISSUE TITLE
Questões na modelagem

### ISSUE THREAD

**Issue by bmarchete** [CartinhaSquadETEC/projeto-distribuidora#9]
Sobre a modelagem @CartinhaSquadETEC 

1. Se você possui métodos de pagamentos, isso não resultaria em uma tabela? De onde vem a informação que é boleto ou cheque?
2. Acho bem estranho vocês colocarem idade como `int`. Isso significa que vocês, todos os dias do ano, vão buscar os clientes que fizeram aniversário e alterar a idade deles. E como vocês sabem se o cliente fez aniversário?
3. Onde está registrado o valor da compra para acompanhar o histórico? Cada vez que muda o valor do jogo, o histórico vai mudar também!

**Comment by CartinhaSquadETEC** [comment]
Sobre a "2.", seria melhor alterar a idade para um variável **data_nascimento**? Pois não seria necessário alterar quando o comprador fizesse aniversário e para encontrar a idade seria apenas calcular
@bmarchete

**Comment by CartinhaSquadETEC** [comment]
Sobre a "3.", esquecemos mesmo de colocar uma variável valor da compra, obrigado por avisar professor
@bmarchete

**Comment by bmarchete** [comment]
Levem isso em consideração @PerfilAluminios. Ainda faltou a consideração da primeira questão que fiz @CartinhaSquadETEC

**Comment by CartinhaSquadETEC** [comment]
O código foi atualizado levando em considerações as questões feitas pelo professor.
Obrigado pela ajuda Rubens, foi levado em consideração as três questões levantadas e foi tudo corrigido, se encontrar algum erro peço-lhe que nos avise para poder consertar o quanto antes.

@bmarchete 
@PerfilAluminios
